lib/_model/wallet.dart, lib/_pkg/wallet/create.dart, lib/main.dart, lib/wallet/bloc/wallet_cubit.dart
The source of this issue was in the `_pkg/wallet/create/loadBdkWallet` function, in which cold card wallets were following the same case as xpub. 
- Added a new case for cold card wallets which do not need to further derive keys.
There were few other issues I noticed along the way, which we can consider fixing as part of this PR:
=> Fixed coldcard descriptor bug

lib/import/bloc/import_cubit.dart, lib/import/bloc/import_state.dart
Fixed second point in : https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/32
Regarding allowing user to correct wrong inputs.
Required resetting cubit errImporting field every time recover is clicked. 
Noticed this pattern required in other projects too where err states need to be set to emptyString every time an attempt is made, especially if logic involves err.emtpyString checks.
=> Reset errImporting, to allow correcting mistakes in Recovery word input

lib/receive/receive_page.dart, lib/send/advanced.dart, lib/send/send_page.dart
Fixed issues
- coin selection should not be allowed if send full wallet balance is selected.
- In recieve - create invoice, if my chosen unit is btc i should be able to set the amount in BTC, right now it only allows setting amount in sats.
=> Disabled coin selection if selecting sweep balance

android/app/build.gradle, android/build.gradle
Update minSdkVersion to 24
Update kotlin [gradle plugin] version to 1.9.0
---
Without these changes, I was getting all sorts of errors building like the following that suggested an upgrade would fix it:
```
> Task :app:compileDebugKotlin FAILED
> Task :app:mergeExtDexDebug
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
> Task :app:mergeExtDexDebug FAILED
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> Compilation error. See log for more details
* Try:
> Run with --stacktrace option to get the stack trace.
> Run …
```
=> Update dependencies to build on macOS

lib/send/send_page.dart
The Confirmed Transaction TxDetailsScreen was taking up the whole screen rather than existing in the flow of the send page, thereby removing the Send button.
This change puts it back into the flow of the page.
before
after
=> Fix Confirmed Transaction Screen rendering

lib/_pkg/wallet/bdk/transaction.dart
This PR fixes some conversion issues between `BigInt` and `int` types in bdk's `getTransactions` function causing it to throw an error and not show the transaction history.
=> fix: BigInt to int conversions

lib/send/send_page.dart
This relies exclusively on two simple if conditionals in _Screen rather than a complex nested one later on. I missed committing this in #341 but it is necessary in order to fix the Confirm TxDetailsScreen
=> Fix TxSuccess conditional

lib/_pkg/payjoin/manager.dart, lib/_pkg/wallet/bdk/sensitive_create.dart, lib/_pkg/wallet/bdk/transaction.dart, lib/_pkg/wallet/transaction.dart, lib/locator.dart, lib/send/advanced.dart, lib/send/bloc/send_cubit.dart, lib/send/bloc/send_state.dart, lib/send/send_page.dart, lib/swap/swap_page.dart, lib/transaction/bump_fees.dart, pubspec.lock, pubspec.yaml
This is a basic sender implementation that may be merged so we can build off of it. It does not include any isolate behavior or do accounting properly. I would like help getting the accounting right by taking data from a signed payjoin and pushing it into the Transaction model @ethicnology.
This separates the signing and "confirmed" stages and marshals successful payjoins to the final screen. I don't think a new payjoin handshake screen is merited until the isolates can allow that behavior to happen outside of the send cubit.
Please see the commit log for hacks taken to get this working. 
For a payjoin send:
I ask reviewers to confirm errors are handled appropriately, since this flutter paradigm is new to me.
=> Send Payjoin

lib/send/send_page.dart
Two different NetworkFeesCubit instances where used between the SendPage and the SendCubit: the SendPage components used a local NetworkFeesCubit to store the fee state, but the global default NetworkFeesCubit was injected in the SendCubit and was used to get the fees on confirmation from, not having the locally set state.
This fixes https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/331.
=> fix: custom manual fee not used in Send

lib/send/bloc/send_cubit.dart
For bip49 it is important to retain letters in lower and uppercase. Removing the toLowerCase() in the correct place makes sure it is and bip49 addresses are correctly scanned and passed to the Send input.
This fixes https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/334.
=> fix: remove address toLowerCase

lib/send/bloc/send_cubit.dart, lib/send/listeners.dart
This small fix hides the 'Send payjoin' switch again if another address without payjoin params is pasted after one that had these params.
When resetting the pj state on a new address, and pasting a pj uri with amount, the currency cubit executed the updateAddress a second time but without the uri, just the address, not setting back the pj params after resetting.
The only reason I can think of that the currency cubit did this was to trigger a _checkBalance, so I changed the condition to check a balance and removed the updateAddress from the currency cubit listener. Now the update address is only executed once, the time with the pj params present.
=> Reset pj state for new addresses

lib/_pkg/payjoin/listeners.dart, lib/_pkg/payjoin/manager.dart, lib/_pkg/payjoin/storage.dart, lib/_pkg/storage/storage.dart, lib/home/listeners.dart, lib/locator.dart, lib/receive/bloc/receive_cubit.dart, lib/send/bloc/send_cubit.dart, pubspec.lock, pubspec.yaml
The whole point of Payoin V2 is to save the state of a payjoin and resume it whenever you have internet. Our first implementation doesn't do that since the logic is limited to the Send or Receive UI context where it's created and it disappears when the app goes out of memory.
This change persists that information in HiveStorage, pauses sessions on app background, and resumes sessions on app foregroudn, allowing async payjoin to happen.
There was a bug where Sender's didn't persist information sent in their first request, so once they were persisted and resumed they were out of sync with receivers. This has been fixed in an upcoming release of payjoin-flutter and so requires that update in order to function.
In order to test, start a receiver, background that app, then start a sender to …
=> Async Payjoin send and receives

lib/receive/bloc/state.dart
This PR removes some code that is executed when payjoinReceiver != null that was present two times in the same function, one time before checking `isLiquid` and one time after checking `isLiquid`. The code before the Liquid check was causing the issue and so I removed it, since if not Liquid, it will still be executed after this check.
A more elaborate fix would also make sure the payjoinReceiver gets reset when isLiquid, but I think a bigger refactoring can eliminate this problem completely, so for now just removing the duplicate code before the check works as a quick fix.
=> fix: remove duplicate payjoin code in getAddressWithAmountAndLabel

lib/receive/bloc/receive_cubit.dart, lib/receive/receive_page.dart
This PR adds the address only without bip21 scheme and parameters underneath the bip21 uri for users to copy for bip21 incompatible wallets.
=> feat: add copying of address only to receive with payjoin

lib/send/listeners.dart
The `updateAddress` with only the address, when a pj uri was entered, was removed in a previous fix already since it was replaced with the following in the `updateAddress` function:
```
if (_currencyCubit.state.amount != 0) {
_checkBalance();
}
```
Executing the _checkBalance function was the only effect calling the updateAddress from the CurrencyCubit listener had, so it got replaced with a check for the amount in the state since it had the undesired side effects of overwriting the address without the bip21 uri scheme, thus not setting the payjoin.
Therefore it got removed again in this PR. As well as the previous CurrencyCubit listener above it that didn't had any useful code anymore.
=> fix: remove repeated updateAddress call without pj uri

lib/_pkg/payjoin/event.dart, lib/_pkg/payjoin/manager.dart, lib/send/bloc/send_cubit.dart, lib/send/bloc/send_state.dart, lib/send/send_page.dart
This PR adds and propogate the necessary events in the sender isolate and `PayjoinEventBus` to know when a payjoin request is successfully posted.
It also uses that event to progress the send flow and show a payjoin success screen.
In this version the cubit doesn't check if the event stems from the send in progress or from another payjoin isolate, since the event doesn't have any data fields yet. So it assumes the event is from the transaction the user is sending at that moment.
In a later version this can be handled by adding some data to the event to check against the send state.
=> feat: send flow pj success screen

lib/_pkg/payjoin/event.dart
While we should create a success screen to display the Payjoin Success with a link to mempool.space, I'm not comfortable linking directly from the alert, since some people might not want to reveal their IP addres to the explorer, and making a stopgap payjoin success screen seems like an unnecessary hack when we plan to follow up with a proper payjoin history.
So this just gets rid of the txid that renders for now.
=> Don't display txid in toast

lib/_pkg/payjoin/event.dart, lib/_pkg/payjoin/manager.dart, lib/send/bloc/send_cubit.dart
- Moves the request_posted message emission till after validating the response from the pj directory.
- Adds a failure event to the PayjoinEventBus and process this in the SendCubit too.
=> Pj send events

lib/send/bloc/send_cubit.dart, lib/send/listeners.dart
This PR exposes the checkBalance function of the SendCubit so it can be called again on amount change with a CurrencyCubit listener, which was previously done by calling the updateAddress function with null and false parameters but caused bugs when entering bip21 URI's.
This fix makes sure the checkBalance is called, triggering enabling or disabling the send button, without the other side effects of calling the updateAddress again.
=> fix: check balance on amount change

lib/_pkg/payjoin/manager.dart
The tryPreservingPrivacy function avoids some varieties of Unnecessary Input Heuristic but sometimes finds no available selection. We always want to contribute an input for the sake of demonstration, and the resulting transaction can't be worse for privacy than a naive transaction, it just might be identifiable as a payjoin.
In the future, we definitely want more sophisticated coin selection, but for now, this makes more payjoins so we get more feedback from testing to make a more reliable, legible product.
=> Select first utxo for payjoin contribution

pubspec.lock, pubspec.yaml
`DanGould/payjoin-flutter` commit `28642ec548278d7e3d724a7518042b816ffd5dae` doesn't exist anymore, probably amended.
Since developers have cached it locally in `.pub-cache`, we can still build without issues, but this wouldn't work for someone which haven't cached it.
Replacing by last active branch `0-22`
=> fix: amended-commit-ref

lib/_pkg/payjoin/event.dart, lib/_pkg/payjoin/manager.dart, lib/_pkg/payjoin/storage.dart, lib/main.dart, lib/receive/bloc/receive_cubit.dart, lib/send/bloc/send_cubit.dart
This PR fixes some of the problems with resuming sessions at startup and with the sessions and isolates in general, namely:
- core.init() was needed in main to be able to reinitiate persisted sessions fromJson
- the resumeSessions now spawns all in parallel since otherwise another stored session couldn't be spawned before the previous was completed. Since it is unsure when a session will complete, it was not good to let all other sessions wait for the previous to complete.
- The completer of the spawnReceiver was never completed and the sessions were never cleaned, so isolates just kept piling up over time.
- The spawnSender didn't complete everywhere I think is necessary either, neither did the clean up work, this is now fixed by using the pjUrl as an identifier to store the isolates and …
=> fix: core.init() for startup resume + remove await + complete and clean up sessions

lib/_pkg/payjoin/manager.dart, lib/_pkg/payjoin/storage.dart
Payjoin sessions marked 'complete' do not get spawned. This reduces the number of isolates spawned on resume or restart.
Mark rather than delete so that the historic status may eventually be shown in transaction history.
=> Mark successful payjoin sessions in storage.

lib/_pkg/payjoin/event.dart, lib/_pkg/payjoin/manager.dart, lib/send/bloc/send_cubit.dart
Sometimes a payjoin error was shown on the send page because of another pj session emitting a `PayjoinFailureEvent` at that time. This PR fixes that by adding a `pjUri` to the event and checking for the same one as the `SendCubit`'s `pjUri`.
=> fix: only show error for current send pj session

lib/receive/bloc/receive_cubit.dart, lib/receive/receive_page.dart
This PR makes sure that loadingAddress is still true when payjoin is enabled and the payjoin receiver is still being initialized.
It then uses the loadingAddress state to show a spinner instead of the QR and addresses as long as it is true, effectively showing the address only when the payjoin uri is also constructed.
=> show spinner while loading payjoin address

lib/_pkg/payjoin/manager.dart, lib/_pkg/payjoin/storage.dart
Mark unrecoverable errors in storage so that they no longer spawn isolates.
Spawning isolates and failing them immediately uses more resources than necessary. This is therefore a performance improvement for the stability of the app.
In the medium term we should switch on errors from payjoin-flutter, but those errors are not yet available to switch on. This will reduce the amount of error definition and handling we have to manually implement, but since this is a potential immediate performance issue I'm addressing it straight away.
=> Mark unrecoverable errors so they don't spawn

lib/_repository/app_wallets_repository.dart, lib/home/bloc/home_bloc.dart, lib/home/bloc/home_event.dart, lib/home/bloc/home_state.dart, lib/home/home_page.dart, lib/home/listeners.dart
This PR:
- creates a stream to get updates about the available wallet services
- subscribes to the wallet services stream and subscribes to the data stream of every wallet service
- changes HomeState to use WalletServiceData instead of Wallet
- Removes the Home Loading Cubit and listeners that were only used to toggle the syncing indicator and just uses a getter from the HomeState instead.
=> use streams to get updates in wallet services and WalletServiceData

lib/ui/themes/app_theme.dart
This pr adds an example of a theme that customises the font height, weight etc. since we will need to do this too following the Figma. It can be used as a reference for that part, the rest of the file can be ignored.
=> add example theme with text height and weight styling

lib/_pkg/payjoin/manager.dart
This fix tries to solve the freezing of the app during startup and syncing that happens when a lot of payjoin isolates are spawned at the same time by adding a delay between isolate spawning.
@i5hi I tried this on an Android emulator, where I was able to get the app to freeze during initial syncing and then not have it freeze anymore with this fix, but I think it would be good to have some thorough tests on a real device still before merging by initiating a lot of sessions and making sure it doesn't freeze anymore on startup/resume of the app. If it still freezes, we might need to increase the delay time, but I think it is better to keep it as low as possible so all payjoin sessions can advance as soon as possible when a user opens the app.
=> fix: add staggering to isolate spawning to avoid freezing of app

lib/_pkg/payjoin/listeners.dart
As far as I know, isolates are backgrounded and resumed together with the main app thread, so I think it is not necessary to kill and resume them explicitly ourselves. Normally they will be paused when the app is backgrounded and resumed when it is foregrounded again.
=> Unnecessary killing and starting of isolates when app is backgrounded

lib/_core/domain/entities/seed.dart, pubspec.lock, pubspec.yaml
- https://pub.dev/packages/bip39 is unmaintained for years and contains outdated dependencies
- https://pub.dev/packages/bip39_mnemonic is maintained internally by me
- bip39_mnemonic handles internationalization features with describe in the bip39 mediawiki
=> Replace bip39 dependency by bip39_mnemonic

lib/_core/data/datasources/payjoin_datasource.dart, lib/_utils/constants.dart
Integration tests were failing and there seems to be a problem with the ohttp relay of bobspace: 'https://pj.bobspacebkk.com'. This PR changes this single relay to a list of relays which now also contains achow's ohttp relay. This makes the integration tests and payjoin work again.
=> use list of ohttp relays in case one is failing

lib/core/bitcoin/data/datasources/bitcoin_blockchain_datasource.dart, lib/core/bitcoin/data/repository/bdk_wallet_repository_impl.dart, lib/core/locator/core_locator_services.dart, lib/core/locator/core_locator_usecases.dart, lib/core/payjoin/data/datasources/payjoin_datasource.dart, lib/core/payjoin/data/models/payjoin_model.dart, lib/core/payjoin/data/repository/payjoin_repository_impl.dart, lib/core/payjoin/data/services/payjoin_watcher_service_impl.dart, lib/core/payjoin/domain/entity/payjoin.dart, lib/core/payjoin/domain/repositories/payjoin_repository.dart, lib/core/payjoin/domain/usecases/broadcast_original_transaction_usecase.dart, lib/core/seed/data/repository/seed_repository_impl.dart, lib/core/utils/transaction_parsing.dart, lib/core/wallet/data/services/wallet_manager_service_impl.dart, lib/features/receive/presentation/bloc/receive_bloc.dart, lib/features/receive/presentation/bloc/receive_event.dart, lib/features/receive/presentation/bloc/receive_state.dart, lib/features/receive/receive_locator.dart, lib/features/receive/ui/receive_router.dart, lib/features/receive/ui/screens/receive_details_screen.dart, lib/features/receive/ui/screens/receive_payjoin_in_progress_screen.dart, lib/features/receive/ui/screens/receive_payment_in_progress_screen.dart, lib/features/receive/ui/screens/receive_payment_received_screen.dart, lib/features/receive/ui/widgets/receive_payment_received_details.dart
This PR adds the payjoin in progress screen when a payjoin request is made and permits the receiver to broadcast the original tx if waiting for the sender is not an option or the payjoin failed on the sender's side.
It also improves the routing and fixes the bug that overwrites fields when switching networks.
=> Receive payjoin progress screens + Receive Routing fixes

lib/features/receive/presentation/bloc/receive_bloc.dart, lib/features/receive/presentation/bloc/receive_state.dart, lib/features/receive/ui/receive_router.dart
This PR now uses only one BLoC for all receive networks + only fetches async data if not in the state yet.
=> Keep the Bitcoin or Liquid address when toggling networks to receive instead of generating a new every time

lib/features/settings/ui/settings_router.dart
The screen of a selected wallet should be a subroute of the wallets list for the wallet details setting, to reflect the navigation better and only have the routes of the main settings screen as the first level routes of the settings routes.
Also to avoid having a path that has two times `wallet-details` when going to the selected wallet through the wallets list from settings.
=> make selected wallet route a subroute of wallet details route

lib/features/app_unlock/ui/pin_code_unlock_screen.dart, lib/features/key_server/ui/screens/confirm_screen.dart, lib/features/key_server/ui/screens/enter_screen.dart, lib/features/key_server/ui/screens/recover_with_secret_screen.dart, lib/features/pin_code/ui/screens/choose_pin_code_screen.dart, lib/features/pin_code/ui/screens/confirm_pin_code_screen.dart, lib/ui/components/dialpad/dial_pad.dart
Adds a field to DialPad to allow disableFeedback. Defaults to false. Set to true for all sensitive features that use DialPad.
=> fix: disableFeedback on dialpad for sensitive PINs

lib/core/exchange/data/models/user_summary_model.dart, lib/core/exchange/domain/entity/order.dart, lib/core/exchange/domain/entity/user_summary.dart, lib/core/utils/amount_formatting.dart, lib/features/buy/buy_locator.dart, lib/features/buy/presentation/buy_bloc.dart, lib/features/buy/presentation/buy_event.dart, lib/features/buy/presentation/buy_state.dart, lib/features/buy/ui/screens/buy_accelerate_screen.dart, lib/features/buy/ui/screens/buy_input_screen.dart, lib/features/buy/ui/widgets/buy_amount_input_fields.dart, lib/features/exchange/presentation/exchange_state.dart
This PR mainly updates the amount input component to be visually more equal to the web exchange and to be able to see the exchange rate and input an amount in bitcoin/sats as well.
It does some other minor refactors for the exchange and amount formatting like:
- Changing the currency in user summary to nullable, since a user that just signed up doesn't seem to have a currency yet and this was throwing an error.
- Show a 0 balance for a newly created user without balances and without a set currency in the set currency of the wallet
- Adding a parameter to the fiat amount formatting to show the amount with the symbol instead of the code
- Adding more currencies to the Order fiat currencies, since balances are returned for them too.
=> Buy amount UI improvements

lib/core/storage/sqlite_database.dart
This PR adds two configurations that could prevent `database locked` errors as mentioned in the Drift docs or from comments in the drift code.
I did a lot of hot reloads, which was when I was experiencing the error in dev before, and until now, with these configuration, I haven't had the error anymore.
=> share instance across isolates and use WAL pragma

lib/core/seed/data/repository/seed_repository.dart, lib/core/storage/migrations/005_hive_to_sqlite/old/old_hive_datasource.dart, lib/core/storage/migrations/005_hive_to_sqlite/secure_storage_datasource.dart, lib/core/storage/secure_storage.dart, lib/core/storage/storage_locator.dart
related: 
_A long outstanding problem with the Android part of this package is the deprecated usage of older cryptography usage (CBC with PKCS5/PKCS7 padding) for SDK < 23, and the already deprecated JetSec Crypto library that is being used for the current implementation of SecureSharedPreferences.
To fix these issues, i am moving to a custom implementation of the JetSec Crypto library, and removing all other deprecated methods of encrypting the shared preferences. This requires the minimum SDK to be raised from 21 to 23.
I am currently testing the new implementation in the [branch ](https://github.com/mogol/flutter_secure_storage/tree/version-10)version-10. Any help is greatly appreciated._
https://pub.dev/packages/flutter_secure_storage#note-usage-of-encryptedsharedpreference
=> feat: prevent errors due to mixed usage of `encryptedSharedPreferences`

lib/features/exchange/ui/exchange_router.dart, lib/features/settings/ui/screens/exchange/exchange_settings_screen.dart, lib/features/settings/ui/settings_router.dart
Redirect to auth from exchange settings for a user who is not logged in.
And show logout button in settings only when the user is logged in, else show login button that navigates to exchange auth screen.
=> Exchange settings no auth

lib/core/wallet/data/repositories/wallet_address_repository.dart
This PR uncomments the address enriching with extra data again, but with one optimization of only fetching all transactions once instead of for every address individually. This solves the earlier problem of crashing due to too many concurrent `isMine` checks.
A lot more optimizations can still be done, for example now the utxo lists are fetched for every address again as well to check the balance, instead of one time to get the balance of all addresses. But at least this can fix the crashing already and still give this extra info for an address.
=> fetch transactions only once to enrich all addresses

lib/features/sell/ui/screens/sell_wallet_selection_screen.dart, lib/features/wallet/ui/widgets/wallet_cards.dart
Hide until we added selling from these types properly.
=> hide external wallets/signers and watch-only wallets to sell from

lib/features/receive/ui/screens/receive_qr_screen.dart, lib/features/wallet/ui/widgets/wallet_home_top_section.dart
This PR fixes the background of the top section of the wallet home which doesn't fill the whole space on ipad.
It also fixes the QR size which is unconstrained and takes up almost the whole screen on ipad.
QR size before:
QR size after:
r:
=> Ipad responsiveness: Full width wallet home top background + constrain QR sizes

lib/features/exchange/ui/screens/exchange_kyc_screen.dart
On the KYC path, we know the page is rendered if the flutterview tabIndex is '-1' and not '0'. Other pages might not have this and therefore might reload since something else than '-1' is returned, for example "<null>". Checking strictly for '0' to know the page is not rendered, solves this.
This PR also enables going from the /kyc flow to /verification flow to not block the user as long as this redirection still happens/is permitted by the web app.
=> fix reloading outside of /kyc path

ios/Podfile.lock, lib/core/wallet/data/repositories/wallet_address_repository.dart, lib/core/wallet/domain/usecases/get_new_receive_address_use_case.dart, lib/features/receive/presentation/bloc/receive_bloc.dart, pubspec.lock
Because of new address generation in swap resolutions, the address stop gap can become exceeded quickly, to already prevent it on Liquid, in which address reuse is less of a concern, we return the last unused as default now by keeping the `forceUnseenLiquidAddress` parameter on false in the `getNewReceiveAddress` function. And only set that param to true if the user explicitly wants to generate another address.
This is a quick fix though, since it is not good to have a param only for Liquid in a function for both bitcoin as liquid wallets.
Also does this not solve the problem for Bitcoin on-chain wallets exceeding the stop gap quickly. Therefore a more thorough solution is needed in the swaps management to only generate one refund address per swap and not more after every reinit of the …
=> default new receive address for liquid to last unused

ios/Podfile.lock, lib/core/swaps/data/datasources/boltz_storage_datasource.dart, lib/core/swaps/data/models/auto_swap_model.dart, lib/core/swaps/data/repository/boltz_swap_repository.dart, lib/core/swaps/domain/entity/auto_swap.dart, lib/core/swaps/domain/usecases/auto_swap_execution_usecase.dart, lib/features/autoswap/autoswap_locator.dart, lib/features/autoswap/presentation/autoswap_settings_cubit.dart, lib/features/autoswap/presentation/autoswap_settings_state.dart, lib/features/autoswap/ui/widgets/autoswap_settings.dart, pubspec.lock
Migration for `recipientWalletId` in autoswap is already completed on develop.
This PR just uses this new field and updates existing functionality to use a provided wallet ID rather than using the default wallet all the time. 
Since the value is set as null in the db; the code will now check for null and replace with defaultBitcoinWalletId; following which this value should never be set to null again. This will ensure existing behaviour does not change.
Users can then change the value in autoswap settings where providing a value for recipientWalletId is required.
=> feat: allow autoswap to any bitcoin walletId

lib/features/backup_settings/backup_settings_locator.dart, lib/features/backup_settings/presentation/cubit/backup_settings_cubit.dart
@i5hi found this error related to hardcoded mainnet network filters that was throwing errors when switching to testnet
=> fix: remove hardcoded network filters in `BackupSettingsCubit`

lib/features/send/presentation/bloc/send_state.dart, lib/features/send/ui/screens/send_screen.dart
The balance check was now also an amount input check, which are two different things, needed in different places, so this PR separates and uses both were needed, for validation and to enable/disable the Continue button.
=> unmix amount input check and balance check

lib/core/widgets/price_input/price_input.dart, lib/features/send/presentation/bloc/send_cubit.dart, lib/features/send/presentation/bloc/send_state.dart, lib/features/send/ui/screens/send_screen.dart
This PR fixes the following things that were causing problems with the send amounts and mainly with MAX amount:
- Make sure the equivalent amount is correct and shown when MAX is set
- Made PriceInput stateless since it didn't manage any state and Stateless is better to be sure re-renders are done if constructor params change
- Don't use the amount textfield to show 'MAX' anymore, just show a Text field when max is set. This makes it less error prone since the amount controller should only have amounts, so text that can be parsed to a numeric value.
- Change the amount when max is set, and switch input currency to a bitcoin unit if it was fiat input
- Keep isMax in the state of the screen to render things like showing the 'MAX' correctly
- Reset the amountConfirmedClicked field if no …
=> fix max amount in send

lib/core/widgets/inputs/text_input.dart
This PR solves the following reported problem:
> When swapping….on the keyboard it doesn’t give me the option to add a period. So to swap 0.0023 for example, i have to either type it elsewhere and copy it or find another way to put a period. 
As a quick fix for this, I added the decimal option to true in BBTextInput, but the real solution to have correct keyboard input, input formatting and validation is to make a better reusable component or reusable functions with a `TextFormField`. We should plan this in the task to review/improve/remove all reusable components and maybe create new reusable components that are more useful than some of the ones we have now. An example of how to use the inputFormatting and validation can already be shown in this pull request for DCA: …
=> make sure the decimal point is shown on numeric iOS keyboards

lib/features/buy/ui/widgets/buy_amount_input_fields.dart
Fixes following reported issue:
> during Buy flow observing that the ‘BTC’ or ‘Fait’ is missing next to the BTC <-> Fiat conversion icon.
=> add currency code to currency toggle in buy amount input

lib/core/themes/app_theme.dart
Fixing this annoying bug
https://github.com/user-attachments/assets/bffd0082-b4a4-46b4-9192-c7b5e40daeab
=> fix: Closes #1042 red/pink overlay when scrolling

lib/features/send/ui/widgets/fee_options_modal.dart
Currently, when entering custom fee amount on iOS the keyboard covers the confirm button which prevents the user from confirming, and closing the keyboard closes the sheet, which prevents completely from setting the custom fee.
This PR fixes the padding when the keyboard is open so the user can confirm the custom fees.
=> Fix confirm button for custom fee unreachable on iOS

integration_test/bip85_derivation_test.dart, integration_test/recoverbull_test.dart, lib/core/bip85/data/bip85_datasource.dart, lib/core/storage/tables/bip85_derivations_table.dart, lib/core/utils/recoverbull_bip85.dart, lib/core/widgets/bip85_derivation_widget.dart, pubspec.lock, pubspec.yaml, test/recoverbull_bip85_test.dart
- Published the dependency as `bip85_entropy` on pub.dev to avoid confusion with the rust bindings published under `bip85`
- Fixed Recoverbull BIP85 derivation path to properly use hardened paths
- **OLD**: `1608'/0'/randomIndex` (missing final `'`)
- **NEW**: `1608'/0'/randomIndex'` (properly hardened)
- Maintains compatibility with existing vaults encrypted using the old path format, while new derivations use the correct hardened path specification.
=> fix: fix the recoverbull path and improve the bip85 integration
