lib/_ui/word_grid.dart, lib/import/bloc/import_cubit.dart, lib/import/bloc/import_state.dart, lib/import/bloc/import_state.freezed.dart, lib/import/page.dart, lib/import/recover.dart, lib/import/recover24.dart, lib/wallet_settings/backup.dart, lib/wallet_settings/bloc/wallet_settings_cubit.dart
Updated the code for 24 import seed words
=> Recover 24 words support

lib/import/recover.dart, lib/import/recover24.dart, lib/transaction/transaction_page.dart
Receive tx page cant bump fee now, fixed a two digit number size on recover wallet
=> Two digits issue on recover wallet and receive tx page disabled bump fee

lib/_ui/wallet_card.dart, lib/_ui/wallet_txs.dart, lib/send/send_page.dart, lib/send/wallet_select.dart
Need reviews,will update UI accordingly
=> Transaction sent animation

lib/send/send_page.dart
Tx sent page is now green on top status bar
=> Updated system top bar when Txsucess

lib/home/home_page.dart, lib/send/send_page.dart
Updated with AnnotedRegion widget for system status bar changes
=> Fixed system staus bar issue

lib/_pkg/consts/configs.dart
changing price API to the production endpoint
http://api.bullbitcoin.com/price
=> Price API update

macos/Flutter/GeneratedPluginRegistrant.swift, macos/Flutter/ephemeral/Flutter-Generated.xcconfig, macos/Flutter/ephemeral/flutter_export_environment.sh, test/wallet_sensitive_create_test.dart, test/wallet_sensitive_create_test.data.dart
First draft of Unit Tests for WalletSensitiveCreate class.
With test data in a separate file.
=> [UnitTest] WalletSensitiveCreate

lib/_ui/components/alert.dart, lib/_ui/components/utils.dart, lib/settings/bloc/broadcasttx_cubit.dart, lib/settings/broadcast.dart
Old error message is still displayed for testing. Can remove it later.
Have to look for the red bg color, that's coming from theme.
=> Alert dialog: Integrated in Setting :: Broadcast page

lib/_pkg/boltz/swap.dart, lib/receive/receive_page.dart, lib/swap/bloc/swap_cubit.dart, lib/swap/bloc/swap_state.dart, lib/swap/bloc/swap_state.freezed.dart
Few Notes:
* newBoltzApi() iniaitlization url needs to be done proper.
* `claimFeesEstimate` and `lockupFees` values needs to be verified in `boltz-dart` if they are right.
=> Dynamic fee calculation 1/2

lib/_model/transaction.dart, lib/_model/transaction.freezed.dart, lib/_model/transaction.g.dart, lib/_pkg/consts/configs.dart, lib/_pkg/wallet/lwk/transaction.dart, lib/network/bloc/state.dart, lib/transaction/transaction_page.dart
Fix for https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/273
Note:
- Not using blindingKey now. Just using empty string for all conversions
=> Liquid: ScriptPubkey to Address; Link to liquid blockchain explorer for Txdetail page

lib/_pkg/storage/migration.dart, lib/_pkg/storage/migration0_1to0_2.dart, lib/_pkg/storage/storage.dart
Logic summarized @ https://docs.google.com/document/d/16iH7PlA6IqnNUNd0NE0rYH4XOVkCLmmhkTrDwjUtWtg/edit
=> App Migration: 0.1 to 0.2

lib/create/confirm_popup.dart
=> Correct Typo confirm_popup.dart

lib/network/bloc/network_cubit.dart
Fix for #322 
Returns a descriptive error message when user tries to add a custom tor node
=> feat(network): add error handling for Tor node connection attempt

lib/_model/swap.dart, lib/_pkg/boltz/swap.dart, lib/_pkg/boltz/types.dart, lib/_pkg/logger.dart, lib/_pkg/wallet/bdk/balance.dart, lib/_pkg/wallet/bdk/network.dart, lib/_pkg/wallet/bdk/sensitive_create.dart, lib/_pkg/wallet/bdk/transaction.dart, lib/_pkg/wallet/bdk/utxo.dart, lib/_pkg/wallet/lwk/transaction.dart, lib/receive/receive_page.dart, lib/send/bloc/send_state.freezed.dart, lib/settings/bloc/broadcasttx_cubit.dart, lib/swap/create_swap_bloc/swap_cubit.dart, pubspec.yaml
This PR addresses compatibility issues and build errors in the project, including:
- BigInt and int Type Mismatches: Resolved compile-time errors where BigInt types were incompatible with int parameters and vice-versa
- Dependency Conflict Resolution: Updated `bdk_flutter` as suggested by @i5hi in https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/332#issuecomment-2452067966
- Downgraded `share_plus` to prevent further conflicts and it's usage in [logger.dart](https://github.com/aniketambore/bullbitcoin-mobile/blob/main/lib/_pkg/logger.dart#L24)
- Addressed several adjustments introduced by this version of `bdk_flutter`
These changes successfully allow the app to build from the source, fully resolving issue #332
=> Resolve type mismatches and dependency conflicts

lib/_pkg/payjoin/manager.dart, lib/_pkg/wallet/transaction.dart, lib/receive/bloc/receive_cubit.dart, lib/receive/bloc/state.dart, lib/receive/receive_page.dart
Spawn a receiver in an cubit, then use the Isolate to give it its own memory.
Commits with ✅ have been smoke tested
=> Receive payjoin

lib/receive/bloc/receive_cubit.dart
this check may be superfluous, what do you think @i5hi ?
=> refactor: check of BaseWalletType

lib/_pkg/payjoin/manager.dart
markSenderrSessionComplete was being used in the Receiver
=> Mark receiver session in receiver

lib/receive/receive_page.dart, lib/wallet/bloc/wallet_bloc.dart
=> Fix no wallet utxos

README.md
Just a few corrections in the `README.md` file
=> FIX: Typos on README.md

ios/Podfile.lock, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/_pkg/backup/_interface.dart, lib/_pkg/backup/google_drive.dart, lib/_pkg/backup/local.dart, lib/_pkg/file_picker.dart, lib/_pkg/wallet/bdk/sensitive_create.dart, lib/_repository/wallet_service.dart, lib/_ui/components/text.dart, lib/_ui/warning.dart, lib/home/bloc/home_state.dart, lib/home/home_page.dart, lib/import/bloc/import_cubit.dart, lib/import/hardware_import_bloc/hardware_import_cubit.dart, lib/main.dart, lib/routes.dart, lib/settings/bloc/broadcasttx_cubit.dart, lib/wallet/wallet_page.dart, lib/wallet/wallet_txs.dart, lib/wallet_settings/bloc/backup_settings_cubit.dart, lib/wallet_settings/bloc/backup_settings_state.dart, lib/wallet_settings/bloc/keychain_cubit.dart, lib/wallet_settings/bloc/keychain_state.dart, lib/wallet_settings/encrypted_vault_backup.dart, lib/wallet_settings/keychain_page.dart, lib/wallet_settings/physical_backup.dart, lib/wallet_settings/wallet_settings_page.dart, linux/flutter/generated_plugins.cmake, pubspec.lock, pubspec.yaml
- Enhanced validation messages for PIN and password inputs
- Improved error handling in keychain recovery process
- Updated UI feedback for better user guidance during backup and recovery operations
=> Enhanced Keychain Recovery and Backup Error Handling

lib/_core/data/models/seed_model.dart, lib/_core/domain/entities/seed.dart, lib/_utils/secret_generator.dart
This PR permits to create a Seed entity directly from the seed bytes.
=> add from bytes constructor for seed

.gitignore, analysis_options.yaml, android/app/build.gradle, android/app/src/main/kotlin/com/example/bb_mobile/MainActivity.kt, android/build.gradle, android/settings.gradle, ios/Podfile.lock, lib/core/payjoin/data/datasources/payjoin_datasource.dart, lib/core/seed/data/repository/seed_repository_impl.dart, lib/core/settings/data/repository/settings_repository_impl.dart, lib/core/storage/data/datasources/key_value_storage/impl/secure_storage_data_source_impl.dart, lib/core/swaps/data/repository/boltz_swap_repository_impl.dart, lib/core/wallet/data/repository/wallet_metadata_repository_impl.dart, lib/core/wallet/data/services/wallet_manager_service_impl.dart, lib/core/wallet/domain/usecases/get_used_receive_addresses_usecase.dart, lib/features/key_server/domain/usecases/trash_backup_key_from_server_usecase.dart, lib/features/onboarding/ui/widgets/recover_backup_button.dart, lib/features/receive/ui/screens/receive_details_screen.dart, lib/features/receive/ui/screens/receive_payjoin_in_progress_screen.dart, lib/features/receive/ui/screens/receive_payment_in_progress_screen.dart, lib/features/receive/ui/screens/receive_payment_received_screen.dart, pubspec.lock, pubspec.yaml
- The project is now compatible with flutter `3.29.X`
- Fix [Deprecated imperative apply of Flutter's Gradle plugins](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)
- I had to remove `flutter_barcode_scanner` since it's not maintained anymore and not compatible with flutter 3.29.X –> https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/375
=> Flutter `3.29.X` and Gradle declarative plugins

lib/core/wallet/data/datasources/bdk_wallet_datasource.dart, lib/core/wallet/data/datasources/lwk_wallet_datasource.dart, lib/core/wallet/wallet_locator.dart
update wallet datasource constructors and add active sync management
=> feat: add active sync completers

integration_test/fixtures/labels.dart, integration_test/label_test.dart, ios/Podfile.lock, lib/core/address/domain/entities/address.dart, lib/core/labels/data/label_model.dart, lib/core/labels/data/label_repository.dart, lib/core/labels/data/label_storage_datasource.dart, lib/core/labels/data/labelable.dart, lib/core/labels/domain/create_label_usecase.dart, lib/core/labels/domain/label_entity.dart, lib/core/labels/labels_locator.dart, lib/core/storage/data/datasources/key_value_storage/impl/shared_preferences_datasource_impl.dart, lib/core/utxo/domain/entities/utxo.dart, lib/core/wallet/data/models/wallet_metadata_model.dart, lib/core/wallet/data/repository/wallet_repository_impl.dart, lib/core/wallet/domain/entity/wallet.dart, lib/core/wallet_transaction/domain/entities/wallet_transaction.dart, lib/features/receive/domain/usecases/create_receive_swap_use_case.dart, lib/features/receive/presentation/bloc/receive_bloc.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
```dart
// TODO(azad): Usecase expects a Labelable untity and Address has no external constructor
// await _createLabelUsecase.execute<Address>(
//   origin: state.wallet!.id,
//   entity: state.addressOrInvoiceOnly, // Type Address expected
//   label: note,
// );é
```
=> Label storage optimization

ios/Podfile.lock, lib/core/payjoin/domain/usecases/send_with_payjoin_usecase.dart, lib/features/receive/ui/screens/receive_amount_screen.dart, lib/features/receive/ui/screens/receive_scaffold.dart, lib/features/receive/ui/widgets/receive_enter_note.dart, lib/features/send/ui/send_screen.dart, lib/ui/components/price_input/price_input.dart
- Fix hovering continue button on receive amount screen
- Fix unfocus from note field on receive amount screen
- Fix address value in confirm send overview
- Fix bottom sheet backgrounds in Shellroutes by using the root navigator
=> Receive and send UI fixes

lib/features/scan/scan_widget.dart
=> feat(scan): enhance camera UI and scanning functionality

lib/features/scan/scan_widget.dart
Adjust camera preview and button positioning
=> feat(scan): improve scan UI layout

pubspec.yaml
=> feat: Use semver. Bump to v5.0.0. :pizza:

lib/features/send/request_identifier/request_identifier_cubit.dart, lib/features/send/request_identifier/request_identifier_screen.dart, lib/features/send/request_identifier/request_identifier_state.dart, lib/features/send/ui/send_router.dart
Transform a scanned / pasted input into a `PaymentRequest` ready to be transmitted/redirect to the future next-send feature step.
cc @i5hi
=> refactor: `request_identifier` decouple the first part of send feature

ios/Podfile.lock, lib/core/swaps/data/repository/boltz_swap_repository.dart, lib/core/swaps/data/services/swap_watcher.dart, lib/core/swaps/domain/services/swap_watcher_service.dart, lib/core/swaps/domain/usecases/process_swap_usecase.dart, lib/core/swaps/domain/usecases/restart_swap_watcher_usecase.dart, lib/core/swaps/domain/usecases/watch_swap_usecase.dart, lib/core/swaps/swaps_locator.dart, pubspec.lock
`develop` is errored since https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/984 got merged likely because of a missing commit containing BoltzSwapRepository and updates
- add missing file `BoltzSwapRepository` (from the old `BoltzSwapRepositoryImpl`)
- update functions with missing `isTestnet` param
- convert `SwapWatcherService` to concrete
- update lock files
=> fix: missing `BoltzSwapRepository` and related changes

lib/core/wallet/domain/entities/wallet.dart, lib/features/send/ui/screens/send_screen.dart, lib/features/settings/ui/screens/bitcoin/wallet_details_screen.dart, lib/features/settings/ui/screens/bitcoin/wallet_options_screen.dart, lib/features/settings/ui/screens/bitcoin/wallets_list_screen.dart, lib/features/swap/presentation/swap_state.dart, lib/features/test_wallet_backup/ui/screens/test_physical_backup_screen.dart, lib/features/wallet/ui/screens/wallet_detail_screen.dart, lib/features/wallet/ui/widgets/wallet_cards.dart
Access wallet settings from wallet page. Also Updated network and address type in address details
=> Access wallet settings from wallet page 

lib/features/buy/presentation/buy_bloc.dart
As requested: Always select instant wallet as default when buying Bitcoin, regardless of amount .
=> add default liquid wallet filter for selected wallet to start buy flow

lib/core/widgets/timers/countdown.dart
To try to fix the issue of the timer starting at 0:00 in a very rare case that I am unable to reproduce.
=> Countdown timer

lib/features/import_watch_only_wallet/presentation/import_method_widget.dart
- link to coinkite
- link to doc
=> feat: add coinkite url to buy device

lib/features/transactions/ui/widgets/transaction_details_status_label.dart
=> change 'Payment received' and 'Payment sent' to 'Receive' and 'Send'

lib/features/exchange/ui/screens/exchange_kyc_screen.dart
=> permit navigation to incodesmile.com for exchange verification

android/app/src/main/AndroidManifest.xml, ios/Podfile.lock, lib/core/seed/data/repository/seed_repository.dart, lib/features/app_startup/app_startup_locator.dart, lib/features/app_startup/domain/usecases/check_for_existing_default_wallets_usecase.dart, lib/features/app_startup/presentation/bloc/app_startup_bloc.dart, lib/features/app_startup/presentation/bloc/app_startup_state.dart, lib/features/app_startup/ui/app_startup_widget.dart, lib/features/test_wallet_backup/domain/usecases/check_backup_usecase.dart, lib/features/test_wallet_backup/test_wallet_backup_locator.dart
- Check for seed at startup when checking for existing wallets to make sure the wallets are usable
- Disable automatic Google backup to avoid remains of previous installation on fresh installs
=> add check for seed of default wallets on startup + disable auto backup

lib/core/widgets/cards/action_card.dart, lib/features/settings/ui/screens/all_settings_screen.dart, lib/router.dart
Fix bug in exchange button routing
=> Proper routes for exchange

lib/core/electrum/data/repository/electrum_server_repository_impl.dart, lib/core/utils/generic_extensions.dart, lib/core/wallet/data/datasources/bdk_wallet_datasource.dart, lib/features/backup_wallet/ui/screens/backup_check_list_screen.dart, lib/features/backup_wallet/ui/screens/choose_encrypted_vault_provider_screen.dart, lib/features/swap/presentation/swap_state.dart, lib/features/test_wallet_backup/ui/screens/choose_encrypted_vault_provider_screen.dart, lib/features/test_wallet_backup/ui/screens/test_physical_backup_screen.dart
=> feat: display time for last physical test and last kown encrypted vault

ios/Runner.xcodeproj/project.pbxproj, lib/core/screens/send_confirm_screen.dart, lib/core/swaps/domain/entity/swap.dart, lib/core/widgets/cards/action_card.dart, lib/core/widgets/cards/info_card.dart, lib/features/autoswap/ui/widgets/autoswap_settings.dart, lib/features/exchange/ui/screens/exchange_landing_screen_v2.dart, lib/features/settings/ui/screens/bitcoin/bitcoin_settings_screen.dart, lib/features/swap/ui/swap_page.dart, lib/features/transactions/ui/screens/transaction_details_screen.dart, lib/features/transactions/ui/widgets/ongoing_swaps.dart, lib/features/transactions/ui/widgets/swap_progress_indicator.dart, lib/features/transactions/ui/widgets/swap_status_description.dart, lib/features/transactions/ui/widgets/transaction_details_status_label.dart, lib/features/transactions/ui/widgets/transaction_details_table.dart, lib/features/transactions/ui/widgets/txs_filter_row.dart, lib/features/wallet/ui/widgets/auto_swap_fee_warning.dart, pubspec.yaml
- New UI for Transfers features 
- Update exchange landing text
=> Updated Transfer* UI and references.
